/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'thokle' at '26-08-16 23:04' with Gradle 2.6
 *
 * @author thokle, @date 26-08-16 23:04
 */


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
